server:
  port : 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      # https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
      ddl-auto: create-drop

  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
