INSERT INTO PRODUCT (ID, META_DATA, NAME, ONLINE_ID, PAGE_TITLE, URL_NAME) VALUES (1, 'META_DATA', 'Product 1', '001-000', 'PAGE_TITLE', 'URL_NAME');

INSERT INTO VARIANT_PRODUCT (ID, DELIVERY_TIME, ERP_ID, NAME, ONLINE_ID, ORDER_ID, PRICE) VALUES ( 1, 5, 0010001, 'Product 1 - Variant1', '001-001', 1, 599.0);
INSERT INTO VARIANT_PRODUCT_DOWNLOADS (VARIANT_PRODUCT_ID, DOWNLOADS) VALUES ( 1, 'Product1-Variant1-Download1');
INSERT INTO VARIANT_PRODUCT_DOWNLOADS (VARIANT_PRODUCT_ID, DOWNLOADS) VALUES ( 1, 'Product1-Variant1-Download2');
INSERT INTO VARIANT_PRODUCT_IMAGES  (VARIANT_PRODUCT_ID, IMAGES) VALUES ( 1, 'Product1-Variant1-Images1');

INSERT INTO PRODUCT_VARIANT_PRODUCTS (PRODUCT_ID, VARIANT_PRODUCTS_ID) VALUES ( 1, 1 );
